Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson
// Descrição   : Descobre o antecessor de um número através de uma subtração
// Autor(a)    : Guilherme Gomes Branco Bravo
// Data atual  : 24/08/2021
Var
valor:inteiro
antecessor:inteiro

Inicio
Escreva ("digite um número: ")
leia (valor)
antecessor <- valor - 1
escreva ("O antecessor de",valor," é: ",antecessor)

Fimalgoritmo
