Algoritmo "Equanto-professor"
// Disciplina  :  [Lógica de Programação e Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Gomes Branco Bravo
// Data atual  : 01/09/2021
Var
   // Seção de Declarações das variáveis
   c: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto c < 10 faca
      escreval ("Jailson")
      c <- c + 1
   fimenquanto

Fimalgoritmo
